# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: roberta.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='roberta.proto',
  package='pb',
  syntax='proto3',
  serialized_options=b'Z\003/pb',
  serialized_pb=b'\n\rroberta.proto\x12\x02pb\"-\n\nmodDataLog\x12\r\n\x05label\x18\x01 \x01(\t\x12\x10\n\x08\x64\x65\x63ision\x18\x02 \x01(\x02\"(\n\tmodSecLog\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\"3\n\x11modSecIntlRequest\x12\x1e\n\x07metrics\x18\x01 \x03(\x0b\x32\r.pb.modSecLog\"6\n\x12modSecIntlResponse\x12 \n\x08response\x18\x01 \x03(\x0b\x32\x0e.pb.modDataLog2G\n\nmodSecIntl\x12\x39\n\x06\x44\x65tect\x12\x15.pb.modSecIntlRequest\x1a\x16.pb.modSecIntlResponse\"\x00\x42\x05Z\x03/pbb\x06proto3'
)




_MODDATALOG = _descriptor.Descriptor(
  name='modDataLog',
  full_name='pb.modDataLog',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='label', full_name='pb.modDataLog.label', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='decision', full_name='pb.modDataLog.decision', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=21,
  serialized_end=66,
)


_MODSECLOG = _descriptor.Descriptor(
  name='modSecLog',
  full_name='pb.modSecLog',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='pb.modSecLog.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='pb.modSecLog.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=68,
  serialized_end=108,
)


_MODSECINTLREQUEST = _descriptor.Descriptor(
  name='modSecIntlRequest',
  full_name='pb.modSecIntlRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='metrics', full_name='pb.modSecIntlRequest.metrics', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=110,
  serialized_end=161,
)


_MODSECINTLRESPONSE = _descriptor.Descriptor(
  name='modSecIntlResponse',
  full_name='pb.modSecIntlResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='response', full_name='pb.modSecIntlResponse.response', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=163,
  serialized_end=217,
)

_MODSECINTLREQUEST.fields_by_name['metrics'].message_type = _MODSECLOG
_MODSECINTLRESPONSE.fields_by_name['response'].message_type = _MODDATALOG
DESCRIPTOR.message_types_by_name['modDataLog'] = _MODDATALOG
DESCRIPTOR.message_types_by_name['modSecLog'] = _MODSECLOG
DESCRIPTOR.message_types_by_name['modSecIntlRequest'] = _MODSECINTLREQUEST
DESCRIPTOR.message_types_by_name['modSecIntlResponse'] = _MODSECINTLRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

modDataLog = _reflection.GeneratedProtocolMessageType('modDataLog', (_message.Message,), {
  'DESCRIPTOR' : _MODDATALOG,
  '__module__' : 'roberta_pb2'
  # @@protoc_insertion_point(class_scope:pb.modDataLog)
  })
_sym_db.RegisterMessage(modDataLog)

modSecLog = _reflection.GeneratedProtocolMessageType('modSecLog', (_message.Message,), {
  'DESCRIPTOR' : _MODSECLOG,
  '__module__' : 'roberta_pb2'
  # @@protoc_insertion_point(class_scope:pb.modSecLog)
  })
_sym_db.RegisterMessage(modSecLog)

modSecIntlRequest = _reflection.GeneratedProtocolMessageType('modSecIntlRequest', (_message.Message,), {
  'DESCRIPTOR' : _MODSECINTLREQUEST,
  '__module__' : 'roberta_pb2'
  # @@protoc_insertion_point(class_scope:pb.modSecIntlRequest)
  })
_sym_db.RegisterMessage(modSecIntlRequest)

modSecIntlResponse = _reflection.GeneratedProtocolMessageType('modSecIntlResponse', (_message.Message,), {
  'DESCRIPTOR' : _MODSECINTLRESPONSE,
  '__module__' : 'roberta_pb2'
  # @@protoc_insertion_point(class_scope:pb.modSecIntlResponse)
  })
_sym_db.RegisterMessage(modSecIntlResponse)


DESCRIPTOR._options = None

_MODSECINTL = _descriptor.ServiceDescriptor(
  name='modSecIntl',
  full_name='pb.modSecIntl',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=219,
  serialized_end=290,
  methods=[
  _descriptor.MethodDescriptor(
    name='Detect',
    full_name='pb.modSecIntl.Detect',
    index=0,
    containing_service=None,
    input_type=_MODSECINTLREQUEST,
    output_type=_MODSECINTLRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_MODSECINTL)

DESCRIPTOR.services_by_name['modSecIntl'] = _MODSECINTL

# @@protoc_insertion_point(module_scope)
